version: '3.8'

services:
  # Servicio de base de datos MySQL
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  # Servicio de Flask (API)
  flask:
    build: .
    container_name: flask
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_DB: testdb
    networks:
      - backend

  # Servicio de NGINX (Proxy inverso)
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "3232:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
